package net.isaac.got.common.block;

import net.fabricmc.fabric.api.registry.FlammableBlockRegistry;

public class GOTFlammableBlockRegistry {
    public static void registerFlammableBlocks() {
        FlammableBlockRegistry registry = FlammableBlockRegistry.getDefaultInstance();

        registry.add(GOTBlocks.Arid_Grass, 30, 60);
        registry.add(GOTBlocks.Asshai_Flower, 30, 60);
        registry.add(GOTBlocks.Asshai_Grass, 30, 60);
        registry.add(GOTBlocks.Asshai_Moss, 30, 60);
        registry.add(GOTBlocks.Asshai_Thorn, 30, 60);
        registry.add(GOTBlocks.Blackroot, 30, 60);
        registry.add(GOTBlocks.Bluebell, 30, 60);
        registry.add(GOTBlocks.Asshai_Grass, 30, 60);
        registry.add(GOTBlocks.Corn_Stalk, 30, 60);
        registry.add(GOTBlocks.Corn_Stalk_Corn, 30, 60);
        registry.add(GOTBlocks.Cucumber, 30, 60);
        registry.add(GOTBlocks.Dead_Marsh_Plant, 30, 60);
        registry.add(GOTBlocks.Double_Flower_Black_Iris, 30, 60);
        registry.add(GOTBlocks.Double_Flower_Pink, 30, 60);
        registry.add(GOTBlocks.Double_Flower_Red, 30, 60);
        registry.add(GOTBlocks.Double_Flower_Yellow_Iris, 30, 60);
        registry.add(GOTBlocks.Essos_Flower_Daisy, 30, 60);
        registry.add(GOTBlocks.Essos_Flower_Pink, 30, 60);
        registry.add(GOTBlocks.Essos_Flower_Red, 30, 60);
        registry.add(GOTBlocks.Essos_Flower_Red2, 30, 60);
        registry.add(GOTBlocks.Essos_Flower_Yellow, 30, 60);
        registry.add(GOTBlocks.Flax, 30, 60);
        registry.add(GOTBlocks.Fruit_Leaves_Apple, 30, 60);
        registry.add(GOTBlocks.Fruit_Leaves_Cherry, 30, 60);
        registry.add(GOTBlocks.Fruit_Leaves_Mango, 30, 60);
        registry.add(GOTBlocks.Fruit_Leaves_Pear, 30, 60);
        registry.add(GOTBlocks.Fruit_Sapling_Apple, 30, 60);
        registry.add(GOTBlocks.Fruit_Sapling_Cherry, 30, 60);
        registry.add(GOTBlocks.Fruit_Sapling_Mango, 30, 60);
        registry.add(GOTBlocks.Fruit_Sapling_Pear, 30, 60);
        registry.add(GOTBlocks.Fruit_Wood_Apple, 5, 20);
        registry.add(GOTBlocks.Fruit_Wood_Cherry, 5, 20);
        registry.add(GOTBlocks.Fruit_Wood_Mango, 5, 20);
        registry.add(GOTBlocks.Fruit_Wood_Pear, 5, 20);
        registry.add(GOTBlocks.Catalpa_Leaves, 30, 60);
        registry.add(GOTBlocks.Ibbinia_Leaves, 30, 60);
        registry.add(GOTBlocks.Ulthos_Leaves, 30, 60);
        registry.add(GOTBlocks.Ulthos_Red_Leaves, 30, 60);
        registry.add(GOTBlocks.Aramant_Leaves, 30, 60);
        registry.add(GOTBlocks.Banana_Leaves, 30, 60);
        registry.add(GOTBlocks.Beech_Leaves, 30, 60);
        registry.add(GOTBlocks.Holly_Leaves, 30, 60);
        registry.add(GOTBlocks.Date_Palm_Leaves, 30, 60);
        registry.add(GOTBlocks.Larch_Leaves, 30, 60);
        registry.add(GOTBlocks.Mangrove_Leaves, 30, 60);
        registry.add(GOTBlocks.Maple_Leaves, 30, 60);
        registry.add(GOTBlocks.Baobab_Leaves, 30, 60);
        registry.add(GOTBlocks.Cedar_Leaves, 30, 60);
        registry.add(GOTBlocks.Chestnut_Leaves, 30, 60);
        registry.add(GOTBlocks.Fir_Leaves, 30, 60);
        registry.add(GOTBlocks.Lemon_Leaves, 30, 60);
        registry.add(GOTBlocks.Lime_Leaves, 30, 60);
        registry.add(GOTBlocks.Orange_Leaves, 30, 60);
        registry.add(GOTBlocks.Pine_Leaves, 30, 60);
        registry.add(GOTBlocks.Cypress_Leaves, 30, 60);
        registry.add(GOTBlocks.Mahogany_Leaves, 30, 60);
        registry.add(GOTBlocks.Olive_Leaves, 30, 60);
        registry.add(GOTBlocks.Willow_Leaves, 30, 60);
        registry.add(GOTBlocks.Almond_Leaves, 30, 60);
        registry.add(GOTBlocks.Aspen_Leaves, 30, 60);
        registry.add(GOTBlocks.Fotinia_Leaves, 30, 60);
        registry.add(GOTBlocks.Green_Oak_Leaves, 30, 60);
        registry.add(GOTBlocks.Palm_Leaves, 30, 60);
        registry.add(GOTBlocks.Plum_Leaves, 30, 60);
        registry.add(GOTBlocks.Pomegranate_Leaves, 30, 60);
        registry.add(GOTBlocks.Redwood_Leaves, 30, 60);
        registry.add(GOTBlocks.Dragon_Leaves, 30, 60);
        registry.add(GOTBlocks.Kanuka_Leaves, 30, 60);
        registry.add(GOTBlocks.Weirwood_Leaves, 30, 60);
        registry.add(GOTBlocks.Leek, 30, 60);
        registry.add(GOTBlocks.Lettuce, 30, 60);
    }
}
